param(
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

function Get-GitOutput {
    param([string[]]$Arguments)

    $output = & git @Arguments 2>$null
    if ($LASTEXITCODE -ne 0) {
        return $null
    }
    return $output
}

$repoRoot = Get-GitOutput @("rev-parse", "--show-toplevel")
if (-not $repoRoot) {
    throw "Git repository root could not be found."
}

$repoRoot = ($repoRoot | Select-Object -First 1).Trim()
$contextPath = Join-Path $repoRoot "CONTEXT.md"

if (-not (Test-Path -LiteralPath $contextPath)) {
    throw "CONTEXT.md not found at $contextPath"
}

$branch = (Get-GitOutput @("rev-parse", "--abbrev-ref", "HEAD") | Select-Object -First 1)
$commit = (Get-GitOutput @("rev-parse", "--short", "HEAD") | Select-Object -First 1)
$statusLines = @(Get-GitOutput @("status", "--short"))
$migrationDir = Join-Path $repoRoot "db\migrations"
$recentMigrations = @()

if (Test-Path -LiteralPath $migrationDir) {
    $recentMigrations = Get-ChildItem -LiteralPath $migrationDir -Filter "*.sql" |
        Sort-Object Name |
        Select-Object -Last 10 -ExpandProperty Name
}

$packagePath = Join-Path $repoRoot "frontend\package.json"
$frontendStack = "unknown"
if (Test-Path -LiteralPath $packagePath) {
    $packageJson = Get-Content -Raw -LiteralPath $packagePath | ConvertFrom-Json
    $nextVersion = $packageJson.dependencies.next
    $reactVersion = $packageJson.dependencies.react
    $frontendStack = "Next.js $nextVersion, React $reactVersion"
}

$now = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
$statusPreview = if ($statusLines.Count -gt 0) {
    ($statusLines | Select-Object -First 40 | ForEach-Object { "- ``$_``" }) -join "`n"
}
else {
    "- clean working tree"
}

$migrationPreview = if ($recentMigrations.Count -gt 0) {
    ($recentMigrations | ForEach-Object { "- ``db/migrations/$_``" }) -join "`n"
}
else {
    "- no migration files"
}

$snapshot = @"
<!-- AUTO_CONTEXT_START -->
## Auto Snapshot

This section is generated by scripts/update-context.ps1. Keep stable project knowledge above this section.

- Last updated: $now
- Branch: ``$branch``
- Commit: ``$commit``
- Frontend stack: $frontendStack

### Recent Migrations

$migrationPreview

### Working Tree

$statusPreview

### Refresh

~~~bash
powershell -ExecutionPolicy Bypass -File .\scripts\update-context.ps1
~~~

Before each commit, .githooks/pre-commit runs this script and stages CONTEXT.md again.
<!-- AUTO_CONTEXT_END -->
"@

$content = Get-Content -Raw -Encoding UTF8 -LiteralPath $contextPath
$pattern = "(?s)<!-- AUTO_CONTEXT_START -->.*<!-- AUTO_CONTEXT_END -->"

if ($content -match $pattern) {
    $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $snapshot })
}
else {
    $content = $content.TrimEnd() + "`r`n`r`n" + $snapshot + "`r`n"
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath $contextPath), $content, $utf8NoBom)

if (-not $Quiet) {
    Write-Host "Updated CONTEXT.md"
}
